stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
      
    outs:
      - C:/Users/Hinnovis/Desktop/Kidney_Diseease_Classification_MLFLOW_DVC/artifacts/data_ingestion/datasets


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
      - params/params.yaml
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/cnnClassifier/pipeline/stage_03_training_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_training_model.py
      - config/config.yaml
      - artifacts/data_ingestion/datasets
      - artifacts/prepare_base_model
      - params/params.yaml
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_04_evaluation_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_evaluation_model.py
      - config/config.yaml
      - artifacts/data_ingestion/datasets
      - artifacts/training/model.h5
      - params/params.yaml
    
    metrics:
    - scores.json:
        cache: false